// app/layout.tsx
import { Metadata } from "next";
import MobileWarning from "@/components/MobileWarning";
import "./globals.css";

export const metadata: Metadata = {
  title: "alanotero.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MobileWarning />
        {children}
      </body>
    </html>
  );
}
